version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    expose:
      - 5000
    environment:
      - APP_PORT=5000
      - NODE_ENV=development
      - DB_USERNAME=mark
      - DB_PASSWORD=gobully
      - DB_HOST=drmarkthrasher-zsius.mongodb.net
      - DB_NAME=thrashomatic
      - JWT_SECRET=this_is_my_secret_for_jwt_token_generation
    ports:
      - 5000:5000
    volumes:
      - ./server/src:/app/server/src
    command: node -r esm src/index.js
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    links:
      - server
    command: npm run start
    restart: always
